<?php


/**
 * Content for the Forum footer navigation block. 
 * Block defined in the malmo_forum module
 */
function malmo_forum_footer_nav() {
	return "
		<nav>
	    <ul class='list-1'>
	      <li><a href='/''>TODO</a></li>
	      <li><a href='/''>TODO</a></li>
	    </ul>

	    <ul class='list-2'>
	      <li><a href='/'>TODO</a></li>
	      <li><a href='/''>TODO</a></li>
	    </ul>
	    <ul class='list-3'>
	      <li><a href='/'>TODO</a></li>
	    </ul>
	  </nav>";
}