<?php 

/**
 * Malmö stad assets config file
 */

$assets_config = array( 
	// Your local fully qualified domain name
	"domainname_local" => "www.local.malmo.se",

	// Your local development assets url
	"assetsurl_local" => "www.local.malmo.se:3001/assets",

	// Malmö stad assets url
	"assetsurl_prod" => "webapps06.malmo.se/assets-3.0",

	// Which assets to use in your test environment, "local" or "prod"
	"testenv_assets" => "local"
);