<?php

/**
 * @file
 * Support module for Malmö Stad forum
 */

require_once( drupal_get_path('theme', 'malmostad') . "/block/block-content-functions.inc" );

/**
 * Implementation of hook_block_info().
 */
function malmo_forum_block_info() {    
  $blocks['forum_footer_nav'] = array(
    'info' => t('Forum footer navigation'),
  );

  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function malmo_forum_block_view($delta = '') {
	$block = '';
  switch ($delta) {
    case 'forum_footer_nav':
    	$block['subject'] = '';
      $block['content'] = malmo_forum_footer_nav();
      break;
  }

  return $block;
}


/**
 * Implementation of hook_menu_alter().
 */
function malmo_forum_menu_alter(&$items) {
  
  // Page add/edit container only available to super admin 
  $items['admin/structure/forum/add/container']['access arguments'] = array('access administration pages');
  $items['admin/structure/forum/edit/container/%taxonomy_term'] = array('access administration pages'); 

  // Place add forum as tab menu
  $items['admin/structure/forum/add/forum']['type'] = MENU_LOCAL_TASK;

  // Remove settings from tab menu
  $items['admin/structure/forum/settings']['type'] = MENU_NORMAL_ITEM;
}

